name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Osbertpro@1976
          MYSQL_DATABASE: cakeaddicts
          MYSQL_USER: root
          MYSQL_PASSWORD: Osbertpro@1976
        ports:
          - 3306:3306
        options: "--health-cmd='mysqladmin ping --silent' --health-interval=10s --health-timeout=5s --health-retries=3"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.0'

    - name: Set environment variables
      run: |
        echo "DJANGO_ENV=staging" >> $GITHUB_ENV  # Set the environment to staging
        echo "MYSQL_DB_NAME=cakeaddicts" >> $GITHUB_ENV
        echo "MYSQL_DB_USER=root" >> $GITHUB_ENV
        echo "MYSQL_DB_PASSWORD=Osbertpro@1976" >> $GITHUB_ENV
        echo "MYSQL_DB_HOST=127.0.0.1" >> $GITHUB_ENV

    - name: Install MySQL client libraries
      run: sudo apt-get install -y libmysqlclient-dev  # Install MySQL dev tools

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up the database
      run: |
        mysql --host=127.0.0.1 --user=root --password=Osbertpro@1976 -e "CREATE DATABASE IF NOT EXISTS cakeaddicts;"

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && success()  # Only deploy if the build is successful
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Cakeaddicts-staging'  # Your web app name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
