name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.0'

    - name: Set environment variables
      run: |
        echo "DJANGO_ENV=staging" >> $GITHUB_ENV  # Set the environment to staging
        echo "MYSQL_DB_NAME=cakeaddicts" >> $GITHUB_ENV
        echo "MYSQL_DB_USER=${{ secrets.MYSQL_DATABASE_USER }}" >> $GITHUB_ENV
        echo "MYSQL_DB_PASSWORD=${{ secrets.MYSQL_DATABASE_PASSWORD }}" >> $GITHUB_ENV
        echo "MYSQL_DB_HOST=mystagingdb.mysql.database.azure.com" >> $GITHUB_ENV

    - name: Install MySQL client libraries
      run: sudo apt-get install -y libmysqlclient-dev  # Install MySQL dev tools

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && success()  # Only deploy if the build is successful
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Cakeaddicts-staging'  # Your web app name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
