name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This is your default branch where deployment will trigger

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the OS for the build environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out your code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Adjust based on your application's requirements

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure your dependencies are listed in this file

      - name: Run tests
        run: |
          pytest  # Adjust if using a different test framework or command

  deploy:
    runs-on: ubuntu-latest  # This specifies the OS for the deploy environment
    name: Deploy Our Django Application to Heroku
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checks out the code from the repository

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15  # Heroku deployment action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  # Heroku API key from secrets
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}  # Must be unique in Heroku
          heroku_email: "philbindya55@gmail.com"  # Your Heroku account email
          branch: "main"  # The branch to deploy
