name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This is your default branch where deployment will trigger

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the OS for the build environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out your code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Adjust based on your application's requirements

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure your dependencies are listed in this file

      - name: Run tests
        run: |
          pytest  # Adjust if using a different test framework or command

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment only happens after the build job is complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your code again in the deploy job

      #- name: Set up Heroku CLI
       # run: |
          #curl https://cli-assets.heroku.com/install.sh | sh
          #echo "${{ secrets.HEROKU_API_KEY }}" | heroku auth:token

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 

        run: |
          git remote add heroku https://git.heroku.com/cakeaddicts-staging.git
          git push heroku main  # This pushes the code to your Heroku app