name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y default-libmysqlclient-dev

      - name: Install system dependencies on macOS
        if: runner.os == 'macOS'
        run: brew install mysql

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install dependencies
        run: |
            python -m pip install --upgrade pip
            pip cache purge  # Clear pip cache
            pip install --no-cache-dir -r requirements.txt --verbose --retries 5 --timeout 30

      - name: Run migrations
        run: |
          python manage.py migrate
