name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run Vulnerability Scan
        run: |
          pip install bandit
          bandit -r cakeaddicts/

      - name: Generate Test Coverage Report
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report
          coverage html

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage.xml

      - name: Notify on Success
        if: success()
        run: |
          echo "Build and tests succeeded!"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Build or tests failed!"
