# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - cakestore-app

on:
  push:  # Trigger on push events to any branch
    branches: 
      - '**'  # This means all branches
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies and upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install MySQL client libraries (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libmysqlclient-dev

      - name: Install PostgreSQL (macOS)
        if: runner.os == 'macOS'
        run: brew install postgresql

      - name: Install PostgreSQL (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Zip artifact for deployment
        run: zip release.zip . -r --exclude venv/*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure tests run after build job

    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for testing
        run: unzip -o release.zip

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies for testing
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: pytest

     # - name: Run quality checks (flake8, black, isort, mypy)
     #   run: |
     #     pip install flake8 black isort mypy
      #    flake8 .
      #    black --check .
     #     isort --check-only .
     #     mypy .

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure deploy only runs after tests pass
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'cakestore-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_744358FE4AE045DA8BAA5E73D3513E54 }}
